### PR TITLE
Add pagination title option

### PR DESCRIPTION
**Pull request by vasenin26**
adds the ability to display the signatures on the pagination buttons

### CODE REVIEW

**Comment by bradvin** [comment]
Hi - why are you merging back to my fork?

**Comment by vasenin26** [comment]
I really like your plugin, I use it all the time, but sometimes it does not have enough minutiae and I would like to offer you my ideas on how to make your plugin a little more convenient.

I just started my journey in opensource. Sorry if I did something wrong.

**Comment by bradvin** [comment]
hey @vasenin26  - sorry I should have explained in a bit more detail, and you have done nothing wrong :) It is great that you are contributing back to the open source community so well done!!!

It's just that my fork of OwlCarousel is not the original. I am not the author of OwlCarousel. I forked it a few years ago, and it seems the original fork has been deleted. There is this repo : https://github.com/OwlCarousel2/OwlCarousel2 which is the latest version of the plugin and is being actively updated. That is the version I think you should contribute to

**Comment by vasenin26** [comment]
I understood, thanks for the explanation.

**Pull request closed without merging**
